polygon:
  api_key_ssm_param: "/polygon/apiKey"
  ticker: "AAPL"
  start_date: "2025-01-01"
  end_date: "2025-01-30"
aws:
  iam_profile: "cloud-project-manager"
  s3_bucket: "polygon-stock-data-cloud"
  output_prefix: "full"
rate_limit:
  sleep_seconds: 12