FROM python:3.9-slim

# Set working directory
WORKDIR /cloud_classification

# Install system dependencies for matplotlib
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy project code into the container
COPY . /cloud_classification

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install -r requirements.txt

# Run unit tests 
RUN pytest tests

# Run the pipeline
ENTRYPOINT ["python", "pipeline.py"]
