run_config:
  name: stock-price-prediction
  author: LabSixth
  version: default
  description: Time-series forecasting of APPLE stock closing price in 2024
  dependencies: requirements.txt
  data_source: Polygon Stock API
  output: artifacts/

data_processing:
  data_loading:
    use_s3: false  # Set to true to load data from S3
    local_path: "data/combined_data.parquet"   # Local data file path
    s3_path: "s3://polygon-stock-data-cloud/output/combined_data.parquet"  # S3 data path (if needed)
    bucket_name: polygon-stock-data-cloud
    file_name: output/combined_data.parquet
    column_names:
      - afterHours
      - close
      - from
      - high
      - low
      - open
      - preMarket
      - status
      - symbol
      - volume
      - pull_time
      - source_path
  data_cleaning:
    test_size: 0.2
    date_column: 'from'
    target_column: 'close'

models:
  prophet_model:             # Model type: prophet, chronos, etc.
    horizon: 7
    param_grid: # prophet-specific param grid for optimization
      daily_seasonality: [true, false]
      weekly_seasonality: [true]
      yearly_seasonality: [false]
      seasonality_mode: [additive, multiplicative]
      changepoint_prior_scale: [0.01, 0.05, 0.1, 0.5]
      seasonality_prior_scale: [0.1, 1.0, 5.0, 10.0]
      holidays_prior_scale: [0.1, 1.0, 5.0, 10.0]
    val_size: 0.1
    optimize_objective: ["RMSE"]
  chronos_model:
    horizon: 7
    pretrained_model: "amazon/chronos-t5-tiny"
    device_map: "auto"
    torch_dtype: "bfloat16"
    forecast_type: "median" # "mean" or "quantile"

model_evaluation:
  metrics:
    - RMSE
    - MAE
    - MAPE

aws_outgress:
  bucket_name: "polygon-stock-data-cloud"
  prefix: "artifacts"
  region: "us-east-1"

